
standaloneAddContents({
  code: "castor_2014",
  title: "Concours Castor 2014",
  folder: "2014/",
  difficulties: ["default"],
  tasks: [
    { code: "2014-CH-05-abacus",
      title: "Boulier",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-FR-20-shell",
      title: "Terminal",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-FR-03-monster",
      title: "Attraper le monstre",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-FR-06-bridge",
      title: "Traverser le pont",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-FR-08-maze",
      title: "Deux billes",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-FR-04-gattaca",
      title: "Le défi",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-FR-05-laser",
      title: "Laser",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-SI-02-alien-language",
      title: "Langage alien",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-FR-19-summed-row",
      title: "Position secrète (a)",
      options: {difficulty: "easy"} },
    { code: "2014-FR-19-summed-row",
      title: "Position secrète (b)",
      options: {difficulty: "hard"} },
    { code: "2014-TW-05-summed-area",
      title: "Carte secrète" },
    { code: "2014-AU-02-pancake-flipping",
      title: "Retourner les crêpes",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-NL-01-secret-number",
      title: "Retenir un code",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-SI-04-unknown-friendship",
      title: "Les amis",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-RU-04-carrot-storehouses",
      title: "Pièces d'or",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-CA-02-shout-your-name",
      title: "Discours familiaux",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-SK-01-sticker",
      title: "Autocollants",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-SE-04-height-game",
      title: "Parapente",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-SP-02-traffic",
      title: "Grande réunion",
      difficulties: ["easy", "medium", "hard"] },
    { code: "2014-CH-07-rectangles",
      title: "Dessin interactif",
      difficulties: ["easy", "medium", "hard"] }
   ]
  });


